development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://redistogo:1cf6b3287b1fdfe86f4b793cabe708dc@crestfish.redistogo.com:11445/" } %>
  channel_prefix: ibc-trello_production
